#!/bin/bash
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments

wmake libso libraries/RungeKuttaSchemes

wmake applications/utilities/setTaylorGreenFields

wmake applications/solvers/RKSymFoam
